<?php
/*
 * @author 靳建飞 | e-mail:244029746@qq.com
 * @copyright 靳建飞 2018.3.9 星期5
 * 代币管理：页面；列表；
 */
namespace app\admin\controller;

use app\admin\model\AdminLog;
use app\admin\model\SystemMenu;
use think\Controller;
use think\facade\Session;
use think\Request;
use Env;

class Base extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->assign('getMenuArr',getMenuArr());
        $this->assign('titles','酒水世界-管理后台');
//
        if(in_array($this->request->action(),array('login','logout','captcha','vertify'))){
            return true;
        }else{
            if(Session::get('adm_id','admin')){
                $this->check_priv();//检查管理员菜单操作权限
            }else{

                $this->error('请先登录',url('Admin/login'),1);
            }
        }
    }


    /**
     * 登录权限验证
     * @return bool
     */
    public function check_priv()
    {
        $ctl = $this->request->controller();//当前控制器
        $act = $this->request->action();//当前方法

        $role_list = session('role_list','','admin');
//        dump($role_list);die;
        //无需验证的操作
        $uneed_check = array('pwd_save','login_task');
        if($ctl == 'Index' || $role_list == 'all'){
            //后台首页控制器无需验证,超级管理员无需验证
            return true;
        }elseif(request()->isAjax() || strpos($act,'ajax')!== false || in_array($act,$uneed_check)){
            //所有ajax请求不需要验证权限
            return true;
        }else{
            //获取权限
            $right = SystemMenu::where("sm_id", "in", $role_list)->column('sm_right');

            $role_right = '';
            foreach ($right as $val){
                $role_right .= $val.',';
            }

            $role_right = explode(',', trim($role_right,',')); //转换字符串为数组
            //检查是否拥有此操作权限
            if(!in_array($ctl.'@'.$act, $role_right)){
                $this->error('您没有操作权限['.($ctl.'@'.$act).'],请联系超级管理员分配权限',url('admin/Index/index'),'',1);
            }

        }
    }


    /**
     * 管理日志
     * @param $info
     * @param $url
     */
    public function create_log($info,$url){
        $data['log_admin_id'] = Session::get('adm_id','admin');
        $data['log_admin_username'] = Session::get('adm_username','admin');
        $data['log_url'] = $url;
        $data['log_ip'] = $this->request->ip();
        $data['log_info'] = $info;
        $tt = new AdminLog();
        $tt->save($data);
    }
}
