<?php
namespace app\api\controller;

use app\admin\model\GoodsBrand;

class Goods extends Base
{
    public function initialize()
    {
        /*parent::initialize();*/ // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: ityangs.net");
        header("Access-Control-Allow-Origin: *");
        $post = $this->request->post();
        unset($post['sign']);

        if(!$this->request->post('timestamp') || !$this->request->post('sign') || !$this->request->post('uid')){
            exit(json_encode(array('code'=>4001,'msg'=>'缺少必要参数')));
        }
        if($this->request->post('timestamp') < time()-36000 || $this->request->post('timestamp') > time()+3600) {
            exit(json_encode(array('code'=>4002,'msg'=>'时间戳验证失败')));
        }
        if($this->MakeSign($post) != $this->request->post('sign')){
            exit(json_encode(array('code'=>4000,'msg'=>'签名错误')));
        }
    }
    public function index(){
        $brand = GoodsBrand::where('is_show',0)->order('asort asc')->select();
        foreach($brand as $item){
            $item['icon_url'] = ''.$item['icon'];
        }
    }
}